### ISSUE TITLE
Items repeating

### ISSUE THREAD

**Issue by cyrussutaria** [pbjTEG/TEGMarquee#1]
When implemented, the items in the list keep multiplying. 

    <ul id="feed" class="marqueeContainer">
        <li id="upFirst">First Item</li>
        <li id="upSecond">Second</li>
        <li id="upThird">Third</li>
        <li id="upFourth">Fourth item here</li>
        <li id="upFifth">Fifth</li>
        <li id="upSixth">Six</li>
        <li id="upSeventh">Seven</li>
</ul>

    <script>
        $(document).ready(function() {
            window.TEGMUp = new TEGMarquee({
                marqueeSelector : '#feed',
            });
        TEGMUp.doScroll();
        } );
    </script>

Here is the output
![image](https://user-images.githubusercontent.com/50149473/146090720-cf758c57-d622-4035-880e-4d1b40c583bd.png)

**Comment by pbjTEG** [comment]
Thanks for the heads up. I'll see what I can do.

**Comment by pbjTEG** [comment]
@cyrussutaria ,

I'm finally getting to work on this now that EOY fundraising is winding down. I am unable to recreate the problem with the code provided. 

Can you supply the styles you applied to ul#feed? The size of the viewable area has a great effect upon the scrolling.

**Comment by pbjTEG** [comment]
It might help if I actually publish the docs. I've done that [https://pbjteg.github.io/TEGMarquee/](https://pbjteg.github.io/TEGMarquee/)

**Comment by cyrussutaria** [comment]
> @cyrussutaria ,
> 
> I'm finally getting to work on this now that EOY fundraising is winding down. I am unable to recreate the problem with the code provided.
> 
> Can you supply the styles you applied to ul#feed? The size of the viewable area has a great effect upon the scrolling.

I have used the .css you provided. Here is a snapshot of the element inspected in the browser

![image](https://user-images.githubusercontent.com/50149473/147501213-e386ebbd-6822-42fb-8020-a55940da74f5.png)

**Comment by pbjTEG** [comment]
Reproducible in Chrome; so just for most people.

**Comment by cyrussutaria** [comment]
> Reproducible in Chrome; so just for most people.

Sorry, did you mean you were able to reproduce the issue?

**Comment by pbjTEG** [comment]
@cyrussutaria,

Yes, I was able to recreate on Chrome and Edge. The current version has what I believe to be a fix to the duplication issue and the failure in scrolling down caused by fixing the duplication issue.

If you have time, please let me know if this works for you. Thank you for your help.

**Comment by cyrussutaria** [comment]
Yes, thank you very much . The items appear correctly (only once) now. Issue is resolved.
Happy New Year!
